In [7]:
import numpy as np
from __future__ import absolute_import
from __future__ import print_function
import scipy.io
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from keras.optimizers import SGD, Adadelta, Adagrad
from keras.utils import np_utils, generic_utils
from six.moves import range


In [8]:
X_train = np.load("train_X.npy")
Y_train = np.load("train_binary_Y.npy")
X_test = np.load("valid_test_X.npy")

In [9]:
batch_size = 400
nb_classes = 19
nb_epoch = 150

In [10]:
import numpy as np
 
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.utils import np_utils
from keras.datasets import mnist
 
X_train = np.load("train_X.npy")
Y_train = np.load("train_binary_Y.npy")
X_test = np.load("valid_test_X.npy")
 
# 5. Preprocess input data
#X_train = X_train.reshape(X_train.shape[0], 1, 28, 28)
#X_test = X_test.reshape(X_test.shape[0], 1, 28, 28)
#X_train = X_train.astype('float32')
#X_test = X_test.astype('float32')
#X_train /= 255
#X_test /= 255
 
# 6. Preprocess class labels
#Y_train = np_utils.to_categorical(y_train, 10)
#Y_test = np_utils.to_categorical(y_test, 10)
 
# 7. Define model architecture
model = Sequential()
 
model.add(Convolution2D(32, 3, 3, activation='relu', input_shape=(26,31,23)))
model.add(Convolution2D(32, 3, 3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
 
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
#model.add(Dense(10, activation='softmax'))

model.add(Dense(nb_classes,activation='sigmoid'))



C:\Anaconda\envs\py35\lib\site-packages\ipykernel\__main__.py:28: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(26, 31, 2..., activation="relu")`
C:\Anaconda\envs\py35\lib\site-packages\ipykernel\__main__.py:29: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), activation="relu")`


In [11]:
sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd) 

In [12]:
model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch)

C:\Anaconda\envs\py35\lib\site-packages\keras\models.py:848: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/150
4602/4602 [==============================] - 13s - loss: 6.5517    
Epoch 2/150
4602/4602 [==============================] - 13s - loss: 5.7444    
Epoch 3/150
4602/4602 [==============================] - 13s - loss: 5.3103    
Epoch 4/150
4602/4602 [==============================] - 12s - loss: 4.9787    
Epoch 5/150
4602/4602 [==============================] - 13s - loss: 4.7276    
Epoch 6/150
4602/4602 [==============================] - 12s - loss: 4.5370    
Epoch 7/150
4602/4602 [==============================] - 12s - loss: 4.3971    
Epoch 8/150
4602/4602 [==============================] - 12s - loss: 4.2945    
Epoch 9/150
4602/4602 [==============================] - 12s - loss: 4.1967    
Epoch 10/150
4602/4602 [==============================] - 13s - loss: 4.0467    
Epoch 11/150
4602/4602 [==============================] - 13s - loss: 3.9258    
Epoch 12/150
4602/4602 [==============================] - 12s - loss: 3.8408    
Epoch 13/150
4602/4602 [=============

4602/4602 [==============================] - 12s - loss: 2.6357    
Epoch 103/150
4602/4602 [==============================] - 12s - loss: 2.6271    
Epoch 104/150
4602/4602 [==============================] - 12s - loss: 2.6303    
Epoch 105/150
4602/4602 [==============================] - 11s - loss: 2.6464    
Epoch 106/150
4602/4602 [==============================] - 12s - loss: 2.6310    
Epoch 107/150
4602/4602 [==============================] - 11s - loss: 2.6254    
Epoch 108/150
4602/4602 [==============================] - 11s - loss: 2.6185    
Epoch 109/150
4602/4602 [==============================] - 11s - loss: 2.6279    
Epoch 110/150
4602/4602 [==============================] - 12s - loss: 2.6280    
Epoch 111/150
4602/4602 [==============================] - 12s - loss: 2.6220    
Epoch 112/150
4602/4602 [==============================] - 11s - loss: 2.6132    
Epoch 113/150
4602/4602 [==============================] - 11s - loss: 2.6020    
Epoch 114/150
4602/4602 [=====

In [13]:
x=model.predict(X_train)
print(x[0])
print(Y_train[0])

[  7.45618123e-10   1.55483781e-09   5.45691103e-10   5.13428240e-05
   9.80473123e-06   1.64253322e-06   4.87833418e-09   1.42261060e-05
   1.03441855e-09   9.19953163e-06   4.85206771e-11   2.54906426e-11
   9.81084168e-01   6.37230215e-08   3.29789805e-06   4.84058000e-05
   8.57673222e-05   9.99808013e-01   5.95502936e-09]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]


In [14]:
Y_predicted = model.predict(X_test)
print(Y_predicted[0:5])

[[  2.21870148e-20   2.26754298e-19   1.21623343e-15   3.28240490e-10
    9.98828113e-01   3.05546848e-13   2.84548332e-18   1.82239432e-11
    7.62847739e-20   4.80332433e-17   4.60151685e-23   1.32625921e-18
    1.12270557e-08   1.53182331e-18   1.32363913e-21   2.27143150e-14
    2.20687289e-05   1.00000000e+00   2.75570734e-18]
 [  7.35758229e-15   7.04969090e-15   1.68052218e-14   1.16124852e-06
    9.97464895e-01   1.42212889e-06   4.53724713e-17   4.87392572e-05
    1.35292837e-14   7.76985101e-15   7.63019508e-20   4.38535892e-15
    4.17410746e-07   1.24451068e-15   1.74597613e-19   2.80547493e-14
    6.71490000e-07   1.00000000e+00   6.79645346e-15]
 [  3.40036521e-26   3.99924707e-27   1.14061381e-27   1.05312686e-11
    9.33688023e-12   9.81379569e-01   4.39402072e-28   9.95947897e-01
    2.69065941e-26   4.22413884e-29   2.63622886e-29   9.19371237e-25
    1.60914522e-17   1.91976228e-25   0.00000000e+00   9.45936197e-31
    8.90053002e-07   1.00000000e+00   7.76284552e-26

In [25]:
Y_predicted_binary = np.array([[1 if Y_ele > 0.5 else 0 for Y_ele in Y_row] for Y_row in Y_predicted])

In [27]:
print(Y_predicted_binary[0:5])

[[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0]]


In [28]:
np.save("predicted.npy", Y_predicted_binary)