In [1]:
import numpy as np
from __future__ import absolute_import
from __future__ import print_function
import scipy.io
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from keras.layers.convolutional import Convolution3D, MaxPooling3D
from keras.layers.normalization import BatchNormalization
from keras.optimizers import SGD, Adadelta, Adagrad
from keras.utils import np_utils, generic_utils
from keras.datasets import mnist
from six.moves import range


Using TensorFlow backend.


In [2]:
batch_size = 300
nb_classes = 19
nb_epoch = 100

In [3]:
X_train = np.load("train_X.npy")
Y_train = np.load("train_binary_Y.npy")
X_test = np.load("valid_test_X.npy")

X_train = X_train.reshape(X_train.shape[0], 1, 26, 31, 23)
X_test = X_test.reshape(X_test.shape[0], 1, 26, 31, 23)

# 5. Preprocess input data
#X_train = X_train.reshape(X_train.shape[0], 1, 28, 28)
#X_test = X_test.reshape(X_test.shape[0], 1, 28, 28)
#X_train = X_train.astype('float32')
#X_test = X_test.astype('float32')
#X_train /= 255
#X_test /= 255
 
# 6.Preprocess class labels
# Y_train = np_utils.to_categorical(Y_train, nb_classes)
# Y_test = np_utils.to_categorical(y_test, 10)
 
# 7. Define model architecture
model = Sequential()
 
model.add(Convolution3D(64, (7, 7, 7), input_shape=(1,26,31,23), data_format='channels_first'))
model.add(Activation('relu'))
model.add(MaxPooling3D(pool_size=(2,2,2), strides=(2,2,2)))

model.add(Convolution3D(64, (5, 5, 5)))
model.add(BatchNormalization())
model.add(Activation('relu'))

model.add(Convolution3D(64, (3, 3, 3)))
model.add(BatchNormalization())
model.add(Activation('relu'))
 
model.add(Flatten())
model.add(Dense(1024))
model.add(Activation('relu'))
model.add(Dropout(0.5))
          
model.add(Dense(512))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(25))
#model.add(Dense(10, activation='softmax'))

model.add(Dense(nb_classes,activation='sigmoid'))



In [4]:
sgd = SGD(lr=0.1, decay=1e-6)
model.compile(loss='categorical_crossentropy', optimizer=sgd)

In [5]:
model.fit(X_train, Y_train, batch_size=batch_size, epochs=nb_epoch, verbose = 1)

Epoch 1/100
4602/4602 [==============================] - 25s 5ms/step - loss: 6.1982
Epoch 2/100
4602/4602 [==============================] - 18s 4ms/step - loss: 5.1143
Epoch 3/100
4602/4602 [==============================] - 18s 4ms/step - loss: 4.5485
Epoch 4/100
4602/4602 [==============================] - 18s 4ms/step - loss: 4.2167
Epoch 5/100
4602/4602 [==============================] - 19s 4ms/step - loss: 3.9643
Epoch 6/100
4602/4602 [==============================] - 18s 4ms/step - loss: 3.7721
Epoch 7/100
4602/4602 [==============================] - 19s 4ms/step - loss: 3.6326
Epoch 8/100
4602/4602 [==============================] - 19s 4ms/step - loss: 3.5230
Epoch 9/100
4602/4602 [==============================] - 19s 4ms/step - loss: 3.4281
Epoch 10/100
4602/4602 [==============================] - 19s 4ms/step - loss: 3.2286
Epoch 11/100
4602/4602 [==============================] - 19s 4ms/step - loss: 3.1218
Epoch 12/100
4602/4602 [==============================] - 19s 4

In [6]:
x=model.predict(X_train)
print(x[0])
print(Y_train[0])

[  1.03754726e-04   5.91655498e-06   5.34182959e-07   1.64450589e-03
   2.64043865e-05   2.38670409e-03   1.60958155e-06   1.31721876e-03
   1.38002224e-05   1.37897359e-05   6.96501274e-07   1.24873125e-07
   9.98685062e-01   8.84579822e-06   4.24727614e-06   4.55111967e-06
   7.03390827e-03   9.99993205e-01   4.88232502e-07]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]


In [7]:
Y_predicted = model.predict(X_test)
print(Y_predicted[0:5])

[[  2.57641204e-07   1.31284833e-06   1.20756340e-04   2.61617151e-06
    9.99957800e-01   3.95171668e-07   2.47731514e-05   1.24126700e-06
    4.20567829e-07   1.06168682e-06   2.02097516e-09   3.34164355e-07
    1.27275425e-05   2.37830445e-05   1.61173517e-07   3.93657700e-07
    3.19686681e-02   9.99999762e-01   2.76547610e-07]
 [  1.19011384e-06   2.04243697e-05   5.40455512e-05   2.11808394e-04
    9.99699831e-01   1.34817310e-04   9.30977520e-04   5.91157950e-05
    6.09701128e-05   6.34728030e-06   4.40080953e-07   4.12861154e-05
    6.96617353e-05   5.00671267e-05   3.56577475e-05   1.66837672e-05
    7.73058913e-04   9.99963045e-01   2.81519146e-06]
 [  1.23540212e-05   1.75173234e-04   6.42580322e-10   4.74741173e-05
    2.83855138e-06   9.92033780e-01   3.24114633e-04   9.99868751e-01
    2.15880282e-05   2.02251314e-07   1.15590810e-05   9.29244998e-05
    1.28040820e-05   9.26055145e-05   4.88861005e-08   9.16813789e-08
    1.08060784e-04   9.99997973e-01   8.98391590e-06

In [8]:
Y_predicted_binary = np.array([[1 if Y_ele > 0.5 else 0 for Y_ele in Y_row] for Y_row in Y_predicted])

In [11]:
print(Y_predicted_binary[0:5])

[[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0]]


In [12]:
np.save("Y_predicted.npy", Y_predicted)
np.save("Y_predicted_binary.npy", Y_predicted_binary)